server:
  port: 8092
  
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8092/eureka/ # OVERRIDDEN BY THE DOCKER COMPOSE
