server:
  port: 8091
  error:
    include-stacktrace: NEVER
    include-message: ALWAYS
  

logging:
  pattern:
    file: "%d %p %c{1.} [%t] %m%n"
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
  level:
    org:
      hibernate:
        SQL: DEBUG
  file: app.log
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8092/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: false
    instanceId: ${eureka.instance.hostname}:${server.port}

springdoc:
  swagger-ui:
    urls:
      - name: hotel-services
        url: /hotel-services/api-docs
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true

spring:
  cloud:
    gateway:
      # default-filters:
      #   - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      # globalcors:
      #   add-to-simple-url-handler-mapping: true
      #   corsConfigurations:
      #     "[/**]":
      #       allowed-origins: "*"
      #       allowed-methods: "*"
      #       allowed-headers: "*" 
      discovery:
        locator:
          enabled: true
      routes:
        - id: hotel-services
          uri: lb://hotel-services
          predicates:
            - Path=/hotel-services/**
          filters:
            - RewritePath=/hotel-services/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs