server:
  port: 8091
  error:
    include-stacktrace: NEVER
    include-message: ALWAYS
  
logging:
  pattern:
    file: "%d %p %c{1.} [%t] %m%n"
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
  level:
    org:
      hibernate:
        SQL: DEBUG
  file: app.log
  
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8092/eureka/ # OVERRIDDEN BY THE DOCKER COMPOSE
  # instance:
  #   hostname: localhost
  #   prefer-ip-address: false
  #   instanceId: ${eureka.instance.hostname}:${server.port}

springdoc:
  swagger-ui:
    urls:
      - name: hotel-services
        url: /hotel-services/api-docs
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: hotel-services
          uri: lb://hotel-services
          predicates:
            - Path=/hotel-services/**
          filters:
            - RewritePath=/hotel-services/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs