server:
  error:
    include-stacktrace: NEVER
    include-message: ALWAYS
  port: "0"

springdoc:
  api-docs:
    path: /api-docs
  packagesToScan: com.hotel.booking
  
spring:
  jpa:
    properties:
      hibernate:
        format_sql: "true"
    hibernate:
      ddl-auto: update
    show-sql: "true"
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://hotel-services-db:3306/hotel-services-db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: admin

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8092/eureka/  # OVERRIDDEN BY THE DOCKER COMPOSE
  # instance:
  #   prefer-ip-address: true
  #   instance-id: ${spring.application.name}:${random.uuid}
