server:
  error:
    include-stacktrace: NEVER
    include-message: ALWAYS
  port: "0"

springdoc:
  api-docs:
    path: /api-docs
  packagesToScan: com.hotel.booking
spring:
  jpa:
    properties:
      hibernate:
        format_sql: "true"
    hibernate:
      ddl-auto: update
    show-sql: "true"
  datasource:
    # url: jdbc:mysql://127.0.0.1:3306/user-services
    url: jdbc:mysql://127.0.0.1:3306/hotel-services
    username: root
    password: admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8092/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: false
    instanceId: ${eureka.instance.hostname}:${server.port}