server:
    port: 8098
spring:
    profiles:
        active: native
    application:
        name: config-service
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always